-- ==============================================================
-- ESQUEMA de iam_db  (extraido del estado ACTUAL en vivo)
-- Generado con SMO. NO editar a mano salvo necesidad.
-- ==============================================================
USE [iam_db];
GO

-- ---------- TABLAS ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FAMILIES](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_FAMILIES] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_FAMILIES_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_FAMILIES_Name] ON [dbo].[FAMILIES]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FAMILIES] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[FAMILIES] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[FAMILIES]  WITH CHECK ADD  CONSTRAINT [CK_FAMILIES_Name_NotEmpty] CHECK  ((len([Name])>(0)))
GO
ALTER TABLE [dbo].[FAMILIES] CHECK CONSTRAINT [CK_FAMILIES_Name_NotEmpty]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PATENTS](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[Description] [nvarchar](500) NULL,
	[CreatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_PATENTS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_PATENTS_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_PATENTS_Name] ON [dbo].[PATENTS]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PATENTS] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[PATENTS] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[PATENTS]  WITH CHECK ADD  CONSTRAINT [CK_PATENTS_Name_NotEmpty] CHECK  ((len([Name])>(0)))
GO
ALTER TABLE [dbo].[PATENTS] CHECK CONSTRAINT [CK_PATENTS_Name_NotEmpty]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PATENTS_FAMILIES](
	[PatentId] [uniqueidentifier] NOT NULL,
	[FamilyId] [uniqueidentifier] NOT NULL,
	[AssignedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_PATENTS_FAMILIES] PRIMARY KEY CLUSTERED 
(
	[PatentId] ASC,
	[FamilyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_PATENTS_FAMILIES_FamilyId] ON [dbo].[PATENTS_FAMILIES]
(
	[FamilyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_PATENTS_FAMILIES_PatentId] ON [dbo].[PATENTS_FAMILIES]
(
	[PatentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PATENTS_FAMILIES] ADD  DEFAULT (getdate()) FOR [AssignedDate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](255) NOT NULL,
	[Role] [nvarchar](50) NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[LastLoginDate] [datetime] NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_USERS_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_USERS_IsActive] ON [dbo].[USERS]
(
	[IsActive] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_USERS_Name] ON [dbo].[USERS]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((1)) FOR [IsActive]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [CK_USERS_Name_NotEmpty] CHECK  ((len([Name])>(0)))
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [CK_USERS_Name_NotEmpty]
GO
ALTER TABLE [dbo].[USERS]  WITH CHECK ADD  CONSTRAINT [CK_USERS_Password_MinLength] CHECK  ((len([Password])>=(4)))
GO
ALTER TABLE [dbo].[USERS] CHECK CONSTRAINT [CK_USERS_Password_MinLength]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS_FAMILIES](
	[UserId] [uniqueidentifier] NOT NULL,
	[FamilyId] [uniqueidentifier] NOT NULL,
	[AssignedDate] [datetime] NOT NULL,
	[AssignedBy] [uniqueidentifier] NULL,
 CONSTRAINT [PK_USERS_FAMILIES] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[FamilyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_USERS_FAMILIES_FamilyId] ON [dbo].[USERS_FAMILIES]
(
	[FamilyId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_USERS_FAMILIES_UserId] ON [dbo].[USERS_FAMILIES]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[USERS_FAMILIES] ADD  DEFAULT (getdate()) FOR [AssignedDate]
GO

-- ---------- FOREIGN KEYS ----------
ALTER TABLE [dbo].[PATENTS_FAMILIES]  WITH CHECK ADD  CONSTRAINT [FK_PATENTS_FAMILIES_Family] FOREIGN KEY([FamilyId])
REFERENCES [dbo].[FAMILIES] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PATENTS_FAMILIES] CHECK CONSTRAINT [FK_PATENTS_FAMILIES_Family]
GO
ALTER TABLE [dbo].[PATENTS_FAMILIES]  WITH CHECK ADD  CONSTRAINT [FK_PATENTS_FAMILIES_Patent] FOREIGN KEY([PatentId])
REFERENCES [dbo].[PATENTS] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PATENTS_FAMILIES] CHECK CONSTRAINT [FK_PATENTS_FAMILIES_Patent]
GO
ALTER TABLE [dbo].[USERS_FAMILIES]  WITH CHECK ADD  CONSTRAINT [FK_USERS_FAMILIES_Family] FOREIGN KEY([FamilyId])
REFERENCES [dbo].[FAMILIES] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USERS_FAMILIES] CHECK CONSTRAINT [FK_USERS_FAMILIES_Family]
GO
ALTER TABLE [dbo].[USERS_FAMILIES]  WITH CHECK ADD  CONSTRAINT [FK_USERS_FAMILIES_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[USERS] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[USERS_FAMILIES] CHECK CONSTRAINT [FK_USERS_FAMILIES_User]
GO
