-- ==============================================================
-- ESQUEMA de core_db  (extraido del estado ACTUAL en vivo)
-- Generado con SMO. NO editar a mano salvo necesidad.
-- ==============================================================
USE [core_db];
GO

-- ---------- TABLAS ----------
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEMS](
	[Id] [uniqueidentifier] NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Unit] [nvarchar](50) NULL,
	[IntegerUnit] [bit] NOT NULL,
	[ItemsCategoryId] [int] NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
	[CurrentStock] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_ITEMS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ITEMS_Nombre] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ITEMS] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[ITEMS] ADD  CONSTRAINT [DF_ITEMS_Unit]  DEFAULT ('') FOR [Unit]
GO
ALTER TABLE [dbo].[ITEMS] ADD  DEFAULT ((1)) FOR [IntegerUnit]
GO
ALTER TABLE [dbo].[ITEMS] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
ALTER TABLE [dbo].[ITEMS] ADD  DEFAULT ((0.00)) FOR [CurrentStock]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ITEMS_CATEGORY](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_ITEMS_CATEGORY] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_ITEMS_CATEGORY_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDER_ROWS](
	[Id] [uniqueidentifier] NOT NULL,
	[ReplacementOrderId] [uniqueidentifier] NOT NULL,
	[ItemId] [uniqueidentifier] NOT NULL,
	[Quantity] [decimal](18, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ORDER_ROWS] ADD  DEFAULT (newid()) FOR [Id]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCT_DETAILS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[ItemId] [uniqueidentifier] NOT NULL,
	[QuantityToConsume] [decimal](18, 4) NOT NULL,
 CONSTRAINT [PK_PRODUCT_DETAILS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_PRODUCT_DETAILS_ProductItem] UNIQUE NONCLUSTERED 
(
	[ProductId] ASC,
	[ItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Code] [int] NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_PRODUCTS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_PRODUCTS_Code] UNIQUE NONCLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PRODUCTS] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVIDERS](
	[Id] [uniqueidentifier] NOT NULL,
	[CUIT] [nvarchar](512) NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[CompanyName] [nvarchar](300) NOT NULL,
	[ItemsCategoryId] [int] NOT NULL,
	[ContactTel] [nvarchar](512) NULL,
	[Email] [nvarchar](512) NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_PROVIDERS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PROVIDERS] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[PROVIDERS] ADD  DEFAULT (getdate()) FOR [CreatedDate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PURCHASE_ORDERS](
	[Id] [uniqueidentifier] NOT NULL,
	[ReplacementOrderId] [uniqueidentifier] NOT NULL,
	[Status] [nvarchar](50) NOT NULL,
	[BillFilePath] [nvarchar](500) NULL,
	[TotalAmount] [decimal](18, 2) NOT NULL,
	[IssuedDate] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PURCHASE_ORDERS] ADD  DEFAULT (newid()) FOR [Id]
GO
ALTER TABLE [dbo].[PURCHASE_ORDERS] ADD  DEFAULT (getdate()) FOR [IssuedDate]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REPLACEMENT_ORDERS](
	[Id] [uniqueidentifier] NOT NULL,
	[ReplacementOrderNumber] [nvarchar](100) NOT NULL,
	[ProviderId] [uniqueidentifier] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[REPLACEMENT_ORDERS] ADD  DEFAULT (newid()) FOR [Id]
GO

-- ---------- FOREIGN KEYS ----------
ALTER TABLE [dbo].[ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_ITEMS_ItemsCategoryId] FOREIGN KEY([ItemsCategoryId])
REFERENCES [dbo].[ITEMS_CATEGORY] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ITEMS] CHECK CONSTRAINT [FK_ITEMS_ItemsCategoryId]
GO
ALTER TABLE [dbo].[ORDER_ROWS]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ROWS_ITEMS] FOREIGN KEY([ItemId])
REFERENCES [dbo].[ITEMS] ([Id])
GO
ALTER TABLE [dbo].[ORDER_ROWS] CHECK CONSTRAINT [FK_ORDER_ROWS_ITEMS]
GO
ALTER TABLE [dbo].[ORDER_ROWS]  WITH CHECK ADD  CONSTRAINT [FK_ORDER_ROWS_REPLACEMENT_ORDERS] FOREIGN KEY([ReplacementOrderId])
REFERENCES [dbo].[REPLACEMENT_ORDERS] ([Id])
GO
ALTER TABLE [dbo].[ORDER_ROWS] CHECK CONSTRAINT [FK_ORDER_ROWS_REPLACEMENT_ORDERS]
GO
ALTER TABLE [dbo].[PRODUCT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_DETAILS_Items] FOREIGN KEY([ItemId])
REFERENCES [dbo].[ITEMS] ([Id])
GO
ALTER TABLE [dbo].[PRODUCT_DETAILS] CHECK CONSTRAINT [FK_PRODUCT_DETAILS_Items]
GO
ALTER TABLE [dbo].[PRODUCT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_PRODUCT_DETAILS_Products] FOREIGN KEY([ProductId])
REFERENCES [dbo].[PRODUCTS] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PRODUCT_DETAILS] CHECK CONSTRAINT [FK_PRODUCT_DETAILS_Products]
GO
ALTER TABLE [dbo].[PROVIDERS]  WITH CHECK ADD  CONSTRAINT [FK_PROVIDERS_ItemsCategoryId] FOREIGN KEY([ItemsCategoryId])
REFERENCES [dbo].[ITEMS_CATEGORY] ([Id])
GO
ALTER TABLE [dbo].[PROVIDERS] CHECK CONSTRAINT [FK_PROVIDERS_ItemsCategoryId]
GO
ALTER TABLE [dbo].[PURCHASE_ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_PURCHASE_ORDERS_REPLACEMENT_ORDERS] FOREIGN KEY([ReplacementOrderId])
REFERENCES [dbo].[REPLACEMENT_ORDERS] ([Id])
GO
ALTER TABLE [dbo].[PURCHASE_ORDERS] CHECK CONSTRAINT [FK_PURCHASE_ORDERS_REPLACEMENT_ORDERS]
GO
ALTER TABLE [dbo].[REPLACEMENT_ORDERS]  WITH CHECK ADD  CONSTRAINT [FK_REPLACEMENT_ORDER] FOREIGN KEY([ProviderId])
REFERENCES [dbo].[PROVIDERS] ([Id])
GO
ALTER TABLE [dbo].[REPLACEMENT_ORDERS] CHECK CONSTRAINT [FK_REPLACEMENT_ORDER]
GO
